//const dotenv=require("dotenv").config();
const express = require("express");
const cors = require("cors");
const bodyParser = require("body-parser");
const app = express();
const path = require("path");
const authRoutes = require("./routes/authRoutes");
const userRoutes = require("./routes/userRoutes");
const profileRoutes = require("./routes/profileRoutes");
const profileViewRoutes = require("./routes/profileViewRoutes");
const changePasswordRoute = require("./routes/changePasswordRoute");
const filterRoutes = require('./routes/filterRoutes');
const likeRoutes = require("./routes/likeRoutes");
const storyRoutes = require("./routes/storyRoutes");
const testimonialRoutes = require("./routes/testimonialRoutes");
//const contactRoutes = require("./routes/contactRoutes");
app.use(cors());
app.use(express.json());
app.use(bodyParser.json());

//app.use("/uploads", express.static(path.join(__dirname, "uploads")));
app.use("/api/auth",authRoutes);
app.use("/api/usersInfo", userRoutes);
app.use("/api/profile", profileRoutes);
app.use("/api/incrementViewCount", profileViewRoutes);
app.use("/api/changePassword", changePasswordRoute);
app.use('/api/filter', filterRoutes);
app.use("/api", likeRoutes);
app.use("/api/success-stories", storyRoutes);
app.use("/api", testimonialRoutes);
//app.use("/api/contact", contactRoutes);
const PORT = 5001;
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));
